<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Logistics\Enums;

class PickupTypeEnum
{
    const C_REGULAR_PICKUP = 'REGULAR_PICKUP';
    const C_SCHEDULED_PICKUP = 'SCHEDULED_PICKUP';
    const C_DROP_OFF = 'DROP_OFF';
}
