<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Logistics\Enums;

class RateRecommendationEnum
{
    const C_BUYER_CHOSEN = 'BUYER_CHOSEN';
    const C_CHEAPEST_ON_TIME = 'CHEAPEST_ON_TIME';
    const C_EBAY_PLUS_OK = 'EBAY_PLUS_OK';
    const C_FASTEST_ON_TIME = 'FASTEST_ON_TIME';
    const C_GUARANTEED_DELIVERY_OK = 'GUARANTEED_DELIVERY_OK';
}
