<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Logistics\Enums;

class ShipmentCancellationStatusEnum
{
    const C_CANCELLATION_REQUESTED = 'CANCELLATION_REQUESTED';
    const C_CANCELLATION_ACCEPTED = 'CANCELLATION_ACCEPTED';
    const C_CANCELLATION_REJECTED = 'CANCELLATION_REJECTED';
}
