<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Logistics\Enums;

class WeightUnitOfMeasureEnum
{
    const C_GRAM = 'GRAM';
    const C_KILOGRAM = 'KILOGRAM';
    const C_OUNCE = 'OUNCE';
    const C_POUND = 'POUND';
}
