<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Logistics\Types;

/**
 *
 * @property \DTS\eBaySDK\Logistics\Types\AdditionalOption[] $additionalOptions
 * @property \DTS\eBaySDK\Logistics\Types\Amount $baseShippingCost
 * @property string $destinationTimeZone
 * @property string $maxEstimatedDeliveryDate
 * @property string $minEstimatedDeliveryDate
 * @property string[] $pickupNetworks
 * @property \DTS\eBaySDK\Logistics\Enum\PickupTypeEnum $pickupType
 * @property string $rateId
 * @property string $shippingCarrierCode
 * @property string $shippingCarrierName
 * @property string $shippingServiceCode
 * @property string $shippingServiceName
 * 
 */
class BaseRate extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'additionalOptions' => [
            'type' => 'DTS\eBaySDK\Logistics\Types\AdditionalOption',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'additionalOptions'
        ],
        'baseShippingCost' => [
            'type' => 'DTS\eBaySDK\Logistics\Types\Amount',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'baseShippingCost'
        ],
        'destinationTimeZone' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'destinationTimeZone'
        ],
        'maxEstimatedDeliveryDate' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'maxEstimatedDeliveryDate'
        ],
        'minEstimatedDeliveryDate' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'minEstimatedDeliveryDate'
        ],
        'pickupNetworks' => [
            'type' => 'string',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'pickupNetworks'
        ],
        'pickupType' => [
            'type' => 'DTS\eBaySDK\Logistics\Enum\PickupTypeEnum',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'pickupType'
        ],
        'rateId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'rateId'
        ],
        'shippingCarrierCode' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shippingCarrierCode'
        ],
        'shippingCarrierName' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shippingCarrierName'
        ],
        'shippingServiceCode' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shippingServiceCode'
        ],
        'shippingServiceName' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shippingServiceName'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
