<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Logistics\Types;

/**
 *
 * @property \DTS\eBaySDK\Logistics\Types\ShipmentCancellation $cancellation
 * @property string $creationDate
 * @property string $labelCustomMessage
 * @property string $labelDownloadUrl
 * @property string $labelSize
 * @property \DTS\eBaySDK\Logistics\Types\Order[] $orders
 * @property \DTS\eBaySDK\Logistics\Types\PackageSpecification $packageSpecification
 * @property \DTS\eBaySDK\Logistics\Types\PurchasedRate $rate
 * @property \DTS\eBaySDK\Logistics\Types\Contact $returnTo
 * @property \DTS\eBaySDK\Logistics\Types\Contact $shipFrom
 * @property string $shipmentId
 * @property string $shipmentTrackingNumber
 * @property \DTS\eBaySDK\Logistics\Types\Contact $shipTo
 */
class Shipment extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'cancellation' => [
            'type' => 'DTS\eBaySDK\Logistics\Types\ShipmentCancellation',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'cancellation'
        ],
        'creationDate' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'creationDate'
        ],
        'labelCustomMessage' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'labelCustomMessage'
        ],
        'labelDownloadUrl' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'labelDownloadUrl'
        ],
        'labelSize' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'labelSize'
        ],
        'orders' => [
            'type' => 'DTS\eBaySDK\Logistics\Types\Order',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'orders'
        ],
        'packageSpecification' => [
            'type' => 'DTS\eBaySDK\Logistics\Types\PackageSpecification',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'packageSpecification'
        ],
        'rate' => [
            'type' => 'DTS\eBaySDK\Logistics\Types\PurchasedRate',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'rates'
        ],
        'returnTo' => [
            'type' => 'DTS\eBaySDK\Logistics\Types\Contact',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'returnTo'
        ],
        'shipFrom' => [
            'type' => 'DTS\eBaySDK\Logistics\Types\Contact',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shipFrom'
        ],
        'shipmentId' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shipmentId'
        ],
        'shipmentTrackingNumber' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shipmentTrackingNumber'
        ],
        'shipTo' => [
            'type' => 'DTS\eBaySDK\Logistics\Types\Contact',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'shipTo'
        ]        
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
