<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Logistics\Types;

/**
 *
 * @property string $cancellationRequestedDate
 * @property \DTS\eBaySDK\Logistics\Enums\ShipmentCancellationStatusEnum $cancellationStatus
 * 
 */
class ShipmentCancellation extends \DTS\eBaySDK\Logistics\Types\BaseRate
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        
        'cancellationRequestedDate' => [
            'type' => 'string',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'cancellationRequestedDate'
        ],
        'cancellationStatus' => [
            'type' => 'DTS\eBaySDK\Logistics\Enums\ShipmentCancellationStatusEnum',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'cancellationStatus'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
